export default {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  CURRENT_USER: 'CURRENT_USER',
  CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
  GET_USERS: 'GET_USERS',
  ITEM_ADDED: 'ITEM_ADDED',
  LOCATION_CHANGED: 'LOCATION_CHANGED',

  // App constants
  ACTIVATE_MENU_ITEM: 'ACTIVATE_MENU_ITEM',

  // Public actions
  PUBLIC_GET_USER_BY_ID: 'PUBLIC_GET_USER_BY_ID',
  PUBLIC_GET_USERS: 'PUBLIC_GET_USERS',

  //Auth actions
  CREATE_NEW_USER: 'CREATE_NEW_USER',
  AUTHENTICATE_REQUEST_START: 'AUTHENTICATE_START',
  AUTHENTICATE_REQUEST_ERROR: 'AUTHENTICATE_REQUEST_ERROR',
  AUTHENTICATE_REQUEST_SUCCESS: 'AUTHENTICATE_REQUEST_SUCCESS',


  GET_CURRENT_USER_LOCATION: 'GET_CURRENT_USER_LOCATION',
  GET_PERFORMERS: 'GET_PERFORMERS',

  ARTIST_RECEIVED: 'ARTIST_RECEIVED',

  CARD_SAVING: 'CARD_SAVING',
  CARD_SAVED: 'CARD_SAVED',

  WITHDRAW_REQUEST_START: 'WITHDRAW_REQUEST_START',
  WITHDRAW_SUCCESS: 'WITHDRAW_SUCCESS',


  PERFORMANCE_START_REQUEST: 'PERFORMANCE_START_REQUEST',
  PERFORMANCE_START_SUCCESS: 'PERFORMANCE_START_SUCCESS',

  PERFORMANCE_STOP_REQUEST: 'PERFORMANCE_STOP_REQUEST',
  PERFORMANCE_STOP_SUCCESS: 'PERFORMANCE_STOP_SUCCESS',

  PERFORMANCE_VALIDATION_REQUEST: 'PERFORMANCE_VALIDATION_REQUEST',
  PERFORMANCE_VALIDATION_SUCCESS: 'PERFORMANCE_VALIDATION_SUCCESS',

  PROFILE_SAVE_START: 'PROFILE_SAVE_START',
  PROFILE_SAVE_SUCCESS: 'PROFILE_SAVE_SUCCESS',

  LOGOUT_REQUEST_START: 'LOGOUT_START',
  LOGOUT_REQUEST_ERROR: 'LOGOUT_REQUEST_ERROR',
  LOGOUT_REQUEST_SUCCESS: 'LOGOUT_REQUEST_SUCCESS',
  
  PASSWORD_RECOVER_REQUEST_START: 'PASSWORD_RECOVER_REQUEST_START',
  PASSWORD_RECOVER_REQUEST_ERROR: 'PASSWORD_RECOVER_REQUEST_ERROR',
  PASSWORD_RECOVER_REQUEST_SUCCESS: 'PASSWORD_RECOVER_REQUEST_SUCCESS',

  PASSWORD_CHANGE_REQUEST_START: 'PASSWORD_CHANGE_REQUEST_START',
  PASSWORD_CHANGE_REQUEST_ERROR: 'PASSWORD_CHANGE_REQUEST_ERROR',
  PASSWORD_CHANGE_REQUEST_SUCCESS: 'PASSWORD_CHANGE_REQUEST_SUCCESS',

  EMAIL_CONFIRMATION_REQUEST_START: 'EMAIL_CONFIRMATION_REQUEST_START',
  EMAIL_CONFIRMATION_REQUEST_ERROR: 'EMAIL_CONFIRMATION_REQUEST_ERROR',
  EMAIL_CONFIRMATION_REQUEST_SUCCESS: 'EMAIL_CONFIRMATION_REQUEST_SUCCESS',
}
