export default {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  CURRENT_USER: 'CURRENT_USER',
  CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
  GET_USERS: 'GET_USERS',
  GET_USER_BY_ID: 'GET_USER_BY_ID',
  ITEM_ADDED: 'ITEM_ADDED',
  LOCATION_CHANGED: 'LOCATION_CHANGED',

  //App constants
  ACTIVATE_MENU_ITEM: 'ACTIVATE_MENU_ITEM'
}